#!/usr/bin/env bash

# Disable screen blanking
xset s off
xset -dpms
xset s noblank

# Optional: hide mouse cursor
unclutter -idle 0.5 &

# Start your Electron app
# TODO: Make path dynamic
npm run start:x11 --prefix /home/sumika/sumika
